config/routes.rb
TestCucumber::Application.routes.draw do
 
 root :to => 'blogs#index'
 resources :blogs
  

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name, :occupation
  has_many :blogs
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :author_id, :body, :title
  belongs_to :author
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author_id, :blog_id, :content
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  	@blogs = Blog.all
  end

  def new
  	@blog = Blog.new
  end

  def create 
    @blog = Blog.create(params[:blog])
    @blog.save
    redirect_to blogs_path
  end

  def edit
  	@blog = Blog.find(params[:id])
  end

  def show
  	@blog = Blog.find(params[:id])
  end

  def update
  	@blog = Blog.find(params[:id])
  	@blog.update_attributes(params[:blog])
  	if @blog.save
  	  redirect_to @blog
  	else
  		render :action => edit
  	end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<%= form_for @blog do |blog|%>
  <%= blog.text_field :title, :id => "title" %>
  <%= blog.text_field :body, :id => "body" %>
  <%= blog.submit "Register", :id => "update" %>
  <% end %>

app/views/blogs/index.html.erb
<% @blogs.each do |blog| %>
<p id = "Test Blog">
<%= link_to "#{blog.title}", blog %></p>
<% end %>

app/views/blogs/new.html.erb
<%= form_for @blog do |blog|%>
  <%= blog.text_field :title, :id => "title" %>
  <%= blog.text_field :body, :id => "body" %>
  <%= blog.submit "Register", :id => "Create" %>
  <% end %>

app/views/blogs/show.html.erb
<%= @blog.title %> </br>
<%= @blog.title %>
<%= link_to "edit", edit_blog_path, :id => "edit blog" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestCucumber</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>